### ISSUE TITLE
Endpoint for "recent transactions"

### ISSUE THREAD

**Issue by JasonBernert** [hackoregon/btc-backend#36]
I'd like an endpoint for the most recently added transactions to Behind The Curtain. I'd like to monitor on a daily basis if any big names pop up or if large amounts are given or received.

**Comment by kwhaler** [comment]
Hi Jason. It would be helpful to define 'recent transactions', 'big names' and 'large amounts'. Logic will have to be written for triggers and alerts. If I am not mistaken the scrapers consume data daily (at 1am I think).

**Comment by JasonBernert** [comment]
Hi Ken! Thanks for the quick response. I bugged @DavideDaniel as well.

More specifically, I was wondering if there could be an endpoint that is a time-based query. For instance, I'd like to see all contributions on 2016-04-03. From there I could write my own parser based off the json file to look for names that I define, because they will most likely change with time. 

Also, @catnik says I can't get this endpoint until I bring in a certain political reporter in to speak with the campaign finance team....

**Comment by DavideDaniel** [comment]
http://54.213.83.132/hackoregon/http/current_candidate_week_transactions/931/ - will yield transactions ranging from date of hitting the endpoint to 7 days back

**Comment by JasonBernert** [comment]
:beers: all around!

**Comment by JasonBernert** [comment]
Woot! I need to clean up some wording and add logic, but I made a little slack bot from the Behind The Curtain API. I'll commit the code a little later today.

![screenshot 2016-04-05 11 27 09](https://cloud.githubusercontent.com/assets/2956240/14293598/20719af6-fb22-11e5-9379-acf322846734.png)

**Comment by DavideDaniel** [comment]
Awesome! This is what I imagined.. maybe we can discuss a feature that has feeds for donors and candidate pages.. or not, the endpoint exists for others to use =)

**Comment by JasonBernert** [comment]
I'm getting a 500 error on these endpoints, but it appears the other endpoints are functioning.

**Comment by DavideDaniel** [comment]
Fixed 
![image](https://cloud.githubusercontent.com/assets/8802938/14616658/339bde28-0560-11e6-98f5-cd1746343095.png)

**Comment by DavideDaniel** [comment]
Hmm it's down again..

**Comment by DavideDaniel** [comment]
Ok @JasonBernert it should be up and running again.. Let us know if it comes down again.

**Comment by JasonBernert** [comment]
Awesome! Thanks @DavideDaniel! 🍻 !

**Comment by JasonBernert** [comment]
Just following up. Here's the Campaign Finance slackbot code! 
https://github.com/JasonBernert/slack-bots/blob/master/Campaign%20Finance%20Bot/financeBot.py

I still have lots to do, but wanted to open it up. 😄

**Comment by DavideDaniel** [comment]
Thanks @JasonBernert!
